// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pcyrxdpaotduuoizgppq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjeXJ4ZHBhb3RkdXVvaXpncHBxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMDE5NzcsImV4cCI6MjA1OTc3Nzk3N30.sNlIC3DZui67Albw4k1e5a73SLbhmimYfxwb7iCkfoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);